services:
  api:
    container_name: sec_cafe_api
    image: sec_cafe_backend:1.0
    ports:
      - "7000:7000"
    command: uvicorn run_api:app --host 0.0.0.0 --port 7000 --workers 4
    volumes:
      - ./src:/app
      - /etc/localtime:/etc/localtime