on: workflow_dispatch
env:
  SERVER: prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build
          tar zcvf dist.tar.gz dist
          cd ..
          tar zcvf backend.tar.gz backend
          tar zcvf deploy.tar.gz deploy
          mkdir upload
          mv frontend/dist.tar.gz backend.tar.gz deploy.tar.gz upload/
      - name: Create deploy dir
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /tmp;mkdir -p deploy
          host: ${{ secrets.DEPLOY_HOST}}
          port: ${{ secrets.DEPLOY_HOST_PORT}}
          username: ${{ secrets.DEPLOY_HOST_USER}}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY}}
      - name: upload code
        uses: appleboy/scp-action@v0.1.7
        with:
          source: upload/*.*
          target: /tmp/deploy/
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{secrets.DEPLOY_HOST_PORT}}
          username: ${{ secrets.DEPLOY_HOST_USER}}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY}}
      - name: deploy ui
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /tmp/deploy;mv upload/* .;tar zxvf backend.tar.gz;tar zxvf dist.tar.gz;tar zxvf deploy.tar.gz;cd deploy;chmod +x deploy.sh;sh deploy.sh -s ui -t /data/www/sec.cafe -e prod --clean
          host: ${{ secrets.DEPLOY_HOST}}
          port: ${{ secrets.DEPLOY_HOST_PORT}}
          username: ${{ secrets.DEPLOY_HOST_USER}}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY}}
      - name: delete code
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rm -rf /tmp/deploy
          host: ${{ secrets.DEPLOY_HOST}}
          port: ${{ secrets.DEPLOY_HOST_PORT}}
          username: ${{ secrets.DEPLOY_HOST_USER}}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY}}
      
